<a href="https://colab.research.google.com/github/tackulus/204426/blob/main/Lab_11_610510531.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Workshop 11: Feature Extraction**
**คำสั่ง**

1.   ศึกษาวิธีการสกัดคุณลักษณะสำหรับข้อมูลรูปภาพต่อไปนี้
2.   ทำโจทย์ปฏิบัติการแต่ละข้อตามคำสั่ง
3.   ตั้งชื่อไฟล์ python notebook นี้ในรูปแบบ Lab_11_XXXXXXXXX.ipynb โดย XXXXXXXXX คือ รหัสนักศึกษา
4.   ทำการดาวน์โหลดและส่งไฟล์ Lab_11_XXXXXXXXX.ipynb ที่เว็บไซต์ http://hw.cs.science.cmu.ac.th 

In [1]:
import pandas as pd
import numpy as np
import os
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import nltk.corpus
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords') 
from nltk.corpus import stopwords
from nltk.corpus import wordnet 
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [2]:
!git clone https://github.com/tackulus/204426.git

Cloning into '204426'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 116 (delta 51), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (116/116), 9.05 MiB | 5.62 MiB/s, done.
Resolving deltas: 100% (51/51), done.


**Text Preprocessing**

In [3]:
def get_wordnet_pos(pos): # Map POS tag to first character lemmatize() accepts
    tag = pos[0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)


In [4]:
# Tokenization - Breaking text into tokens which in turn are small structures or units.
text = "More Chinese manufacturers are looking to Thailand as a production base to avoid US tariffs, based on trends in demand for the Southeast Asian nation’s industrial estates."
tokens = word_tokenize(text)
print(tokens)

['More', 'Chinese', 'manufacturers', 'are', 'looking', 'to', 'Thailand', 'as', 'a', 'production', 'base', 'to', 'avoid', 'US', 'tariffs', ',', 'based', 'on', 'trends', 'in', 'demand', 'for', 'the', 'Southeast', 'Asian', 'nation', '’', 's', 'industrial', 'estates', '.']


In [5]:
# Iteratively change each word to its base form by stemming
pst = PorterStemmer()
StemmingWord = []    # create an empty list to save stemming words
for word in tokens:  # get each work from token
    stw = pst.stem(word)    
    StemmingWord.append(stw)  #append the stemming word to StemmingWord list
print(StemmingWord)    # print result


['more', 'chines', 'manufactur', 'are', 'look', 'to', 'thailand', 'as', 'a', 'product', 'base', 'to', 'avoid', 'US', 'tariff', ',', 'base', 'on', 'trend', 'in', 'demand', 'for', 'the', 'southeast', 'asian', 'nation', '’', 's', 'industri', 'estat', '.']


In [6]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatizedWord = []    # create an empty list to save lemmatized token
pos = nltk.pos_tag(tokens)
for word,p in pos:
    lew = lemmatizer.lemmatize(word,get_wordnet_pos(p))
    lemmatizedWord.append(lew)  # append the word to lemmatized Word list
print(lemmatizedWord)  # print result


['More', 'Chinese', 'manufacturer', 'be', 'look', 'to', 'Thailand', 'a', 'a', 'production', 'base', 'to', 'avoid', 'US', 'tariff', ',', 'base', 'on', 'trend', 'in', 'demand', 'for', 'the', 'Southeast', 'Asian', 'nation', '’', 's', 'industrial', 'estate', '.']


In [7]:
# Remove nuisance characters: punctuation
punctuationSet = [c for c in string.punctuation]+['’']
tokenRemovedNuisance = []
for token in lemmatizedWord:
	if token not in punctuationSet:
		 tokenRemovedNuisance.append(token) 
print(tokenRemovedNuisance)

['More', 'Chinese', 'manufacturer', 'be', 'look', 'to', 'Thailand', 'a', 'a', 'production', 'base', 'to', 'avoid', 'US', 'tariff', 'base', 'on', 'trend', 'in', 'demand', 'for', 'the', 'Southeast', 'Asian', 'nation', 's', 'industrial', 'estate']


In [8]:
# remove stopword
stopwordSet = set(stopwords.words('english')) # get list of stop words
words = []
for word in tokenRemovedNuisance:
	if word not in stopwordSet:
		words.append(word) 	
print(words) # print result


['More', 'Chinese', 'manufacturer', 'look', 'Thailand', 'production', 'base', 'avoid', 'US', 'tariff', 'base', 'trend', 'demand', 'Southeast', 'Asian', 'nation', 'industrial', 'estate']


**Read a dataset**

In [11]:
data = pd.read_csv('/content/204426/dataset/ml_ideas.csv')
data.head()


title
0                      Predicting Freeway Congestion
1  Supervised Learning of Query Term Relevant Pro...
2                                Robotic Arm Control
3                        Network Intrusion Detection
4          Multi-Website Name Coreference Resolution

In [12]:
corpus = data.title.tolist()
print(corpus)

['Predicting Freeway Congestion', 'Supervised Learning of Query Term Relevant Product Recommendations', 'Robotic Arm Control', 'Network Intrusion Detection', 'Multi-Website Name Coreference Resolution', 'Probabilistic Independent Component Analysis for fMRI Data and Validating the Components using Learning Methods', 'Machine learning algorithms for musical instrument recognition ', 'Classification of Network Flows', 'Vision and Learning for Quadruped Robot', 'Selection of Relevant Sites in Single Nucleotide Polymorphism', 'Grammar Acquisition in Natural Languages', 'Neural Network Approach to Option Pricing', 'Unsupervised Learning for DNA Transcription Factors', 'A System for Segmenting Video of Juggling ', 'An EigenFace based approach to classify cell-signaling profiles', 'Motor Skill Learning', 'Reinforced Genre Classification and Vocal Segmentation of Popular Music', 'Feature Selection based on Maximizing the Separability in Gauss Mixture Models', 'A Study on Aging Patterns of NBA 

**Feature Extraction**

In [13]:
def preprocess(text):
  text = text.lower()
  tokens = word_tokenize(text)
  lemmatizer = WordNetLemmatizer()
  lemmatizedWord = []
  pos = nltk.pos_tag(tokens)
  for word,p in pos:
    lew = lemmatizer.lemmatize(word,get_wordnet_pos(p))
    lemmatizedWord.append(lew)
  
  punctuationSet = [c for c in string.punctuation]+['’']
  tokenRemovedNuisance = []
  for token in lemmatizedWord:
	  if token not in punctuationSet:
		  tokenRemovedNuisance.append(token) 
  stopwordSet = set(stopwords.words('english')) # get list of stop words
  words = []
  for word in tokenRemovedNuisance:
	  if word not in stopwordSet:
		  words.append(word)
  return ' '.join(words)

In [23]:
# Bag of Words
vocab_dicts = {'network': 0, 'robotic': 1,  'learning':2, 'clustering':3,'predicting':4}
vectorizer = CountVectorizer(ngram_range=(1,1), preprocessor=preprocess, 	vocabulary=vocab_dicts)
vectorizer_model = vectorizer.fit(corpus)
x_BoW = vectorizer_model.transform(corpus).todense()
print(x_BoW)

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 ...
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:
# TF-IDF
vectorizer = TfidfVectorizer(ngram_range=(1,1), preprocessor=preprocess)
vectorizer_model = vectorizer.fit(corpus)
x_tfidf = vectorizer_model.transform(corpus).todense()
print(x_tfidf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


ปฏิบัติการข้อที่ 1 จงสกัดคุณลักษณะของข้อความในคอลัมน์ review ของชุดข้อมูล movie (ไฟล์ movie_data.csv) โดยใช้วิธีการสกัดคุณลักษณะ Bag of Words และ TF-IDF

In [15]:
#your code here!
movie = pd.read_csv('/content/204426/dataset/movie_data.csv')
movie.head()

review  sentiment
0  I went and saw this movie last night after bei...          1
1  Actor turned director Bill Paxton follows up h...          1
2  As a recreational golfer with some knowledge o...          1
3  I saw this film in a sneak preview, and it is ...          1
4  Bill Paxton has taken the true story of the 19...          1

In [63]:
# Bag of Words
vocab_dicts = {'director': 0, 'cry': 1,  'actor':2, 'action':3, 'role':4}
vectorizer = CountVectorizer(ngram_range=(1,1), preprocessor=preprocess, 	vocabulary=vocab_dicts)
vectorizer_model = vectorizer.fit(movie.review.to_list())
x_BoW = vectorizer_model.transform(movie.review.to_list()).todense()
print(x_BoW)

[[0 1 0 0 0]
 [1 0 1 2 0]
 [0 0 0 0 0]
 ...
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [57]:
# TF-IDF
reviewList = movie.review.to_list()
vectorizer = TfidfVectorizer(ngram_range=(1,1), preprocessor=preprocess)
vectorizer_model = vectorizer.fit(reviewList)
x_tfidf = vectorizer_model.transform(reviewList).todense()
print(x_tfidf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
